services:
  api:
    image: my-api:latest
    ports:
      - "80:8080"
    x-composey:
      cpu: 1024
      memory: 2048
  worker:
    image: my-worker:latest
    x-composey:
      size: medium
      memory: 4096 # Override medium's 2048
