# Adapted from https://github.com/docker/awesome-compose/tree/master/flask-redis
services:
  redis:
    image: redislabs/redismod
    ports:
      - '6379:6379'
  web:
    image: flask-redis-web:latest
    ports:
      - '80:8000'
    environment:
      REDIS_HOST: redis
    depends_on:
      - redis
