#!/usr/bin/env python3
"""Generate examples/doctor/compose.yml from examples/doctor/app.py.

The stopgap has no image build step, so the doctor runs on a public python image
whose command installs deps, decodes the app from a base64 blob, and runs it.
app.py is the readable source; this script embeds it. Re-run after editing app.py.
"""

import base64
import pathlib

HERE = pathlib.Path(__file__).resolve().parent.parent
APP = HERE / "examples" / "doctor" / "app.py"
COMPOSE = HERE / "examples" / "doctor" / "compose.yml"

blob = base64.b64encode(APP.read_bytes()).decode()
run = (
    "pip install --quiet --root-user-action=ignore flask boto3 "
    f"&& echo {blob} | base64 -d > /app.py "
    "&& python /app.py"
)

compose = f"""# GENERATED by scripts/build_doctor.py from app.py — edit app.py, not this.
#
# Stopgap deploy of the composey-doctor probe with no image build: a public
# python image installs flask+boto3, decodes app.py from a base64 blob, and runs
# it. `blobs` (minio) is substituted to S3; composey injects BUCKET_NAME into the
# doctor, which does a real S3 put+get on GET /health. x-composey grace period
# gives the container time to pip-install before ALB health checks are enforced.
services:
  doctor:
    image: python:3.12-slim
    command:
      - /bin/sh
      - -c
      - >-
        {run}
    ports:
      - 80:80
    environment:
      BUCKET_NAME: blobs
      S3_ENDPOINT: http://blobs:9000
      AWS_DEFAULT_REGION: eu-west-2
    depends_on:
      - blobs
    networks:
      - public
    x-composey:
      health_check_grace_period: 180
  blobs:
    image: minio/minio
    networks:
      - private
networks:
  public:
  private:
"""

COMPOSE.write_text(compose)
print(f"wrote {COMPOSE.relative_to(HERE)} ({len(blob)} base64 chars from app.py)")
