# Adapted from https://github.com/docker/awesome-compose/tree/master/nginx-flask-mysql
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10-focal
    restart: always
    networks:
      - backnet
    environment:
      - MYSQL_DATABASE=example
    expose:
      - 3306

  backend:
    image: flask-backend:latest # Replaced build with image for end-to-end Fargate test
    restart: always
    ports:
      - 8000:8000
    networks:
      - backnet
      - frontnet
    depends_on:
      db:
        condition: service_started # Simplified condition for now

  proxy:
    image: nginx-proxy:latest # Replaced build with image
    restart: always
    ports:
      - 80:80
    depends_on: 
      - backend
    networks:
      - frontnet

networks:
  backnet:
  frontnet:
